{"name":"error::os::errno_location","from_trait":false,"arguments":[],"sources":[{"loc":"file: Real(\"src/error.rs\") line 99","kind":{"UnsafeFnCall":"C"}}]}
