{"name":"error::errno::errno_location","from_trait":false,"arguments":[],"sources":[{"loc":"file: Real(\"src/error.rs\") line 76","kind":{"UnsafeFnCall":"C"}}]}
